# Generated by Django 3.0 on 2019-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('good_price', models.FloatField(verbose_name='商品价格')),
            ],
        ),
    ]
