# Generated by Django 3.0 on 2019-12-19 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0002_init_good_and_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="good",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="goodcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
